main/urls.py
from django.urls import path, include
from .views import HomepageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('gradesystem/', HomepageView.as_view(template_name='main/gradesystem.html'), name='gradesystem'),
    path('programs/', HomepageView.as_view(template_name='main/programs.html'), name='programs'),
    path('rules/', HomepageView.as_view(template_name='main/rules.html'), name='rules'),
    path('placementProcedure/', HomepageView.as_view(template_name='main/placementprocedure.html'),
         name='placementProcedure'),
    path('contacts/', HomepageView.as_view(template_name='main/contacts.html'), name='contacts'),
    path('admissions/', HomepageView.as_view(template_name='main/admissions.html'), name='admissions'),
    path('achievements/', HomepageView.as_view(template_name='main/achievements.html'), name='achievements'),
    path('profile/', HomepageView.as_view(template_name='main/prospective.html'), name='profile'),
    path('alumni/', HomepageView.as_view(template_name='main/alumni.html'), name='alumni'),
    path('student_rules/', HomepageView.as_view(template_name='main/student_rules.html'), name='student_rules'),
    path('internships/', HomepageView.as_view(template_name='main/internships.html'), name='internships'),
    path('why_recruit/', HomepageView.as_view(template_name='main/why-recruit.html'), name='why-recruit'),
    path('brochure/', HomepageView.as_view(template_name='main/brochure.html'), name='brochure'),
    path('summary/', HomepageView.as_view(template_name='main/summary.html'), name='summary'),
    path('company_rules/', HomepageView.as_view(template_name='main/company_rules.html'), name='company_rules'),
    path('past_recruiters/', HomepageView.as_view(template_name='main/past_recruiters.html'), name='past_recruiters'),
    path('aipc/', HomepageView.as_view(template_name='main/aipc.html'), name='aipc'),
    path('jaf/', HomepageView.as_view(template_name='main/jaf.html'), name='jaf'),
    path('iaf/', HomepageView.as_view(template_name='main/iaf.html'), name='iaf'),
    path('reachus/', HomepageView.as_view(template_name='main/reachus.html'), name='reachus'),
    path('invitation/', HomepageView.as_view(template_name='main/invitation.html'), name='invitation'),
    path('dir_msg/', HomepageView.as_view(template_name='main/dir_msg.html'), name='dir_msg'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('chairman_msg/', HomepageView.as_view(template_name='main/chairman_msg.html'), name='chairman_msg'),
]

src/spc_django/urls.py
from django.urls import path, include
from django.contrib import admin
from accounts.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

admin.site.site_title = 'SPC Administration'
admin.site.site_header = 'SPC Administration'
admin.site.index_title = 'Admin Panel'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('student/', include('student.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            html_email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>[0-9A-Za-z_-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/student/urls.py
from django.urls import path
from .views import DetailsView, ResumeView, InternshipOffersView, JobOffersView, InquirysFormView, SuggestionsFormView
from accounts.views import StudentRegisterFormView

app_name = 'student'

urlpatterns = [
    path('details/', DetailsView.as_view(), name="detail"),
    path('intern_offers/', InternshipOffersView.as_view(), name='intern-offers'),
    path('job_offers/', JobOffersView.as_view(), name='job-offers'),
    path('resume_upload/', ResumeView.as_view(), name='resume_upload'),
    path('register/', StudentRegisterFormView.as_view(), name='register'),
    path('inquiry/', InquirysFormView.as_view(), name='inquiry'),
    path('suggestion/', SuggestionsFormView.as_view(), name='suggestion'),
]

student/urls.py
from django.urls import path
from .views import DetailsView, ResumeView, InternshipOffersView, JobOffersView
from accounts.views import StudentRegisterFormView

app_name = 'student'

urlpatterns = [
    path('details/', DetailsView.as_view(), name="detail"),
    path('intern_offers/', InternshipOffersView.as_view(), name='intern-offers'),
    path('job_offers/', JobOffersView.as_view(), name='job-offers'),
    path('resume_upload/', ResumeView.as_view(), name='resume_upload'),
    path('register/', StudentRegisterFormView.as_view(), name='register'),
]

src/student/models.py
from django.db import models
from django.utils.deconstruct import deconstructible


@deconstructible
class ProgramAndBranch(models.Model):
    name = models.CharField(max_length=60)
    abbreviation = models.CharField(max_length=10)
    usable = models.BooleanField(default=False)

    def __str__(self):
        return self.abbreviation


class ProgramEmailId(models.Model):
    program = models.ForeignKey(ProgramAndBranch, on_delete=models.CASCADE)
    year = models.IntegerField(blank=True, null=True)
    email = models.EmailField()

    def __str__(self):
        return self.email

student/models.py
from django.db import models
from django.utils.deconstruct import deconstructible


@deconstructible
class ProgramAndBranch(models.Model):
    name = models.CharField(max_length=60)
    abbreviation = models.CharField(max_length=10)
    usable = models.BooleanField(default=False)

    def __str__(self):
        return self.abbreviation

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Resume
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from .models import CompanyProfile, StudentProfile
from student.models import ProgramAndBranch


class ResumeForm(forms.ModelForm):
    file = forms.FileField()

    class Meta:
        model = Resume
        fields = ('file', 'reference', 'student')


class StudentRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Enter the same password as before, for verification.',
    )
    username = forms.CharField(max_length=11, help_text="Enter your Roll number, this will be used to login")
    year = forms.IntegerField(max_value=10, help_text="Enter value between 1-5, the current year of your degree")
    #program_branch = forms.ModelChoiceField(queryset=ProgramAndBranch.objects.all())
    gpa = forms.FloatField(max_value=10.00)
    ug_gpa = forms.FloatField(max_value=10.00, required=False)
    phone = forms.CharField(max_length=15)
    dob = forms.DateField()
    category = forms.ChoiceField(choices=StudentProfile.CATEGORY)
    jee_air = forms.IntegerField(required=False)
    physical_disability = forms.BooleanField(required=False)
    nationality = forms.ChoiceField(choices=StudentProfile.NATION)
    permanent_address = forms.CharField(widget=forms.Textarea)
    current_address = forms.CharField(widget=forms.Textarea)
    x_year = forms.IntegerField(max_value=2050, min_value=1980)
    x_board_name = forms.CharField(max_length=100)
    x_percentage = forms.CharField(max_length=10)
    xii_year = forms.IntegerField(max_value=2050, min_value=1980)
    xii_board_name = forms.CharField(max_length=100)
    xii_percentage = forms.CharField(max_length=16)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email']


class CompanyRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Enter the same password as before, for verification.',
    )
    username = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'maxlength': '254'}),
        help_text="This Email ID will be your username")
    name = forms.CharField(max_length=50, help_text="Name of the company")
    domain = forms.CharField(max_length=15, help_text="Type of company like banking/consulting etc ", required=False)
    url = forms.CharField(required=False)
    city = forms.CharField(max_length=15, required=False)
    state = forms.CharField(max_length=15, required=False)
    country = forms.ChoiceField(choices=CompanyProfile.NATION)
    pin_code = forms.CharField(max_length=10, required=False)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

src/student/forms.py
from django import forms
from company.models import JobOffer, InternshipOffer
from accounts.models import Resume, StudentProfile
from django.conf import settings


class JobOfferForm(forms.ModelForm):
    resume = forms.ModelChoiceField(queryset=Resume.objects.none(), empty_label='Select Resume')

    def __init__(self, user, *args, **kwargs):
        super(JobOfferForm, self).__init__(*args, **kwargs)
        resumes = Resume.objects.filter(student__user=user, is_verified=True)
        self.fields['resume'].queryset = resumes

    class Meta:
        model = JobOffer
        fields = ('profile', 'student', 'resume',)


class InternshipOfferForm(forms.ModelForm):
    resume = forms.ModelChoiceField(queryset=Resume.objects.none(), empty_label='Select Resume')

    def __init__(self, user, *args, **kwargs):
        super(InternshipOfferForm, self).__init__(*args, **kwargs)
        resumes = Resume.objects.filter(student__user=user, is_verified=True)
        self.fields['resume'].queryset = resumes

    class Meta:
        model = InternshipOffer
        fields = ('profile', 'student', 'resume',)


class StudentDetailsUpdateForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        fields = (
            'roll_no', 'year', 'gpa', 'ug_gpa', 'phone', 'dob', 'category', 'jee_air',
            'x_year', 'x_board_name', 'x_percentage', 'xii_year', 'xii_board_name', 'xii_percentage',
            'current_address', 'permanent_address', 'nationality', 'physical_disability',
        )
    roll_no = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'style': 'color: black;'}))
    year = forms.IntegerField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    gpa = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    ug_gpa = forms.FloatField(required=False, widget=forms.TextInput(attrs={'style': 'color: black;'}))
    x_year = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    x_board_name = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    x_percentage = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    xii_year = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    xii_board_name = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    xii_percentage = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    dob = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    jee_air = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'style': 'color: black;'}))
    current_address = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))
    permanent_address = forms.CharField(widget=forms.TextInput(attrs={'style': 'color: black;'}))

    if(settings.ALLOW_DETAILS_UPDATE):
        year.widget.attrs['readonly'] = False
        gpa.widget.attrs['readonly'] = False
        ug_gpa.widget.attrs['readonly'] = False
        x_year.widget.attrs['readonly'] = False
        x_board_name.widget.attrs['readonly'] = False
        x_percentage.widget.attrs['readonly'] = False
        xii_year.widget.attrs['readonly'] = False
        xii_board_name.widget.attrs['readonly'] = False
        phone.widget.attrs['readonly'] = False
        dob.widget.attrs['readonly'] = False
        jee_air.widget.attrs['readonly'] = False
        current_address.widget.attrs['readonly'] = False
        xii_percentage.widget.attrs['readonly'] = False
        permanent_address.widget.attrs['readonly'] = False
    else:
        year.widget.attrs['readonly'] = True
        gpa.widget.attrs['readonly'] = True
        ug_gpa.widget.attrs['readonly'] = True
        x_year.widget.attrs['readonly'] = True
        x_board_name.widget.attrs['readonly'] = True
        x_percentage.widget.attrs['readonly'] = True
        xii_year.widget.attrs['readonly'] = True
        xii_board_name.widget.attrs['readonly'] = True
        phone.widget.attrs['readonly'] = True
        dob.widget.attrs['readonly'] = True
        jee_air.widget.attrs['readonly'] = True
        current_address.widget.attrs['readonly'] = True
        xii_percentage.widget.attrs['readonly'] = True
        permanent_address.widget.attrs['readonly'] = True

student/forms.py
from django import forms
from company.models import JobOffer, InternshipOffer
from accounts.models import Resume


class JobOfferForm(forms.ModelForm):
    resume = forms.ModelChoiceField(queryset=Resume.objects.none(), empty_label='Select Resume')

    def __init__(self, user, *args, **kwargs):
        super(JobOfferForm, self).__init__(*args, **kwargs)
        resumes = Resume.objects.filter(student__user=user, is_verified=True)
        self.fields['resume'].queryset = resumes

    class Meta:
        model = JobOffer
        fields = ('profile', 'student', 'resume',)


class InternshipOfferForm(forms.ModelForm):
    resume = forms.ModelChoiceField(queryset=Resume.objects.none(), empty_label='Select Resume')

    def __init__(self, user, *args, **kwargs):
        super(InternshipOfferForm, self).__init__(*args, **kwargs)
        resumes = Resume.objects.filter(student__user=user, is_verified=True)
        self.fields['resume'].queryset = resumes

    class Meta:
        model = InternshipOffer
        fields = ('profile', 'student', 'resume',)

templates/student/details.html
{% extends 'student/base.html' %}
{% block body %}
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="card">
                <div class="card" id="my-card"><span style="font-size: 1.5rem"> &nbsp;Update Details</span></div>
                <div class="card-block">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-5">
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-user prefix"></i>
                                    <label for="id_roll_no" style="font-size: medium">Roll no:</label> <input
                                        type="text" name="roll_no" value="{{ form.roll_no.value }}" maxlength="8"
                                        required id="id_roll_no" readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-graduation-cap prefix" style="color:cornflowerblue"></i>
                                    <span>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Program: {{ studentprofile.program_branch.name }}</span>
                                    
                                </div>
                                <br>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-percent prefix"></i>
                                    <label for="id_gpa" style="font-size: medium">GPA:</label> <input type="number"
                                                                                                      name="gpa"
                                                                                                      value="{{ form.gpa.value }}"
                                                                                                      step="any"
                                                                                                      required
                                                                                                      id="id_gpa"
                                                                                                      readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-percent prefix"></i>
                                    <label for="id_ug_gpa" style="font-size: medium">U.G. GPA:</label> <input type="number"
                                                                                                      name="ug_gpa"
                                                                                                      value="{{ form.ug_gpa.value }}"
                                                                                                      step="any"
                                                                                                      required
                                                                                                      id="id_ug_gpa"
                                                                                                      readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-phone prefix"></i>
                                    <label for="id_phone" style="font-size: medium">Phone:</label> <input type="text"
                                                                                                          name="phone"
                                                                                                          value="{{ form.phone.value }}"
                                                                                                          maxlength="11"
                                                                                                          required
                                                                                                          id="id_phone"/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-birthday-cake prefix"></i>
                                    {{ form.dob }}
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-graduation-cap prefix"></i>
                                    <span>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JEE AIR: {{ studentprofile.jee_air }}</span>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-blind prefix" style="color:cornflowerblue"></i>
                                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Physical Disability : {{ form.physical_disability }}</span>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-bars prefix" style="color:cornflowerblue"></i>
                                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Category : {{ form.category }}</span>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-flag prefix" style="color:cornflowerblue"></i>
                                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nationality : {{ form.nationality }}</span>
                                </div>
                            </div>
                            <div class="col-lg-1"></div>
                            <div class="col-lg-5">
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-home prefix"></i>
                                    <label for="id_permanent_address" style="font-size: medium">Permanent
                                        address:</label> <textarea name="permanent_address" required rows="10"
                                                                   id="id_permanent_address"
                                                                   cols="40"> {{ form.permanent_address.value }}</textarea>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-home prefix"></i>
                                    <label for="id_current_address" style="font-size: medium">Current address:</label>
                                    <textarea name="current_address" required rows="10" id="id_current_address"
                                              cols="40"> {{ form.current_address.value }}</textarea>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-calendar prefix"></i>
                                    <label for="id_x_year" style="font-size: medium">Class X year:</label> <input
                                        type="number" name="x_year" value="{{ form.x_year.value }}" required
                                        id="id_x_year" readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-calendar prefix"></i>
                                    <label for="id_x_board" style="font-size: medium">Class X Board:</label> <input
                                        type="text" name="x_board_name" value="{{ form.x_board_name.value }}" required
                                        id="id_x_board_naem" readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-percent prefix"></i>
                                    <label for="id_x_percentage" style="font-size: medium">Class X
                                        Percentage/CGPA:</label>
                                    <input
                                            type="text" name="x_percentage" value="{{ form.x_percentage.value }}"
                                            required
                                            id="id_x_percentage" readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-calendar prefix"></i>
                                    <label for="id_xii_year" style="font-size: medium">Class XII year:</label> <input
                                        type="number" name="xii_year" value="{{ form.xii_year.value }}" required
                                        id="id_xii_year" readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-calendar prefix"></i>
                                    <label for="id_xii_board" style="font-size: medium">Class XII Board:</label> <input
                                        type="text" name="xii_board_name" value="{{ form.xii_board_name.value }}"
                                        required id="id_xii_board_name" readonly/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-percent prefix"></i>
                                    <label for="id_xii_percentage" style="font-size: medium">Class XII
                                        Percentage/CGPA:</label>
                                    <input type="text" name="xii_percentage" value="{{ form.xii_percentage.value }}"
                                           required id="id_xii_percentage" readonly/>
                                </div>
                                <br>
                            </div>
                        </div>
                        <center>
                            <button class="btn btn-primary" type="submit"> Update</button>
                        </center>
                    </form>
                </div>
            </div>

        </div>
        <div class="col-lg-1">
        </div>
    </div>
    </div>

{% endblock %}

templates/student/login.html
{% extends 'main/base.html' %}
{% block body %}
    <div class="col-lg-3"></div>
    <div class="col-lg-4">
        <div class="card">
            <div class="card" id="my-card"><span style="font-size: 1.5rem"> <center>Student Login</center> </span></div>
            <div class="card-block">
                <br>
                <form method="post">
                    <!--Header-->
                    {% csrf_token %}
                    <div class="md-form">
                        <i class="fa fa-envelope prefix" style="color: #4285F4  "></i>
                        <input type="text" name="username" id="username" class="form-control">
                        <label for="username">Username</label>
                    </div>
                    <div class="md-form">
                        <i class="fa fa-lock prefix" style="font-size: 2.5rem; color: #4285F4   "></i>
                        <input type="password" name="password" id="password" class="form-control">
                        <label for="password">Password</label>
                    </div>
                    {% for error in form.non_field_errors %}
                        <div class="red-text">
                            {{ error }}
                        </div>
                    {% endfor %}
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">Login</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <div class="col-lg-3"></div>



{% endblock %}