company/urls.py
from django.urls import path
from .views import InternshipAdvertisementFormView, JobAdvertisementFormView, InternshipAdvertisementAddedListView, \
    JobAdvertisementsAddedListView, \
    InternshipOfferView, JobOfferView
from accounts.views import CompanyRegisterFormView

app_name = 'company'

urlpatterns = [
    path('intern_offers/', InternshipAdvertisementAddedListView.as_view(), name='intern-offers-added'),
    path('job_offers/', JobAdvertisementsAddedListView.as_view(), name='job-offers-added'),
    path('joboffer_form/', JobAdvertisementFormView.as_view(), name="job-offer-form"),
    path('internoffer_form/', InternshipAdvertisementFormView.as_view(), name="intern-offer-form"),
    path('internship_offer/<uuid:id>/', InternshipOfferView.as_view(), name="internship-offer"),
    path('job_offer/<uuid:id>/', JobOfferView.as_view(), name="job-offer"),
    path('register/', CompanyRegisterFormView.as_view(), name='register'),

]

main/urls.py
from django.urls import path, include
from .views import HomepageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('gradesystem/', HomepageView.as_view(template_name='main/gradesystem.html'), name='gradesystem'),
    path('programs/', HomepageView.as_view(template_name='main/programs.html'), name='programs'),
    path('rules/', HomepageView.as_view(template_name='main/rules.html'), name='rules'),
    path('placementProcedure/', HomepageView.as_view(template_name='main/placementprocedure.html'),
         name='placementProcedure'),
    path('contacts/', HomepageView.as_view(template_name='main/contacts.html'), name='contacts'),
    path('admissions/', HomepageView.as_view(template_name='main/admissions.html'), name='admissions'),
    path('achievements/', HomepageView.as_view(template_name='main/achievements.html'), name='achievements'),
    path('profile/', HomepageView.as_view(template_name='main/prospective.html'), name='profile'),
    path('alumni/', HomepageView.as_view(template_name='main/alumni.html'), name='alumni'),
    path('student_rules/', HomepageView.as_view(template_name='main/student_rules.html'), name='student_rules'),
    path('internships/', HomepageView.as_view(template_name='main/internships.html'), name='internships'),
    path('why_recruit/', HomepageView.as_view(template_name='main/why-recruit.html'), name='why-recruit'),
    path('brochure/', HomepageView.as_view(template_name='main/brochure.html'), name='brochure'),
    path('summary/', HomepageView.as_view(template_name='main/summary.html'), name='summary'),
    path('company_rules/', HomepageView.as_view(template_name='main/company_rules.html'), name='company_rules'),
    path('past_recruiters/', HomepageView.as_view(template_name='main/past_recruiters.html'), name='past_recruiters'),
    path('aipc/', HomepageView.as_view(template_name='main/aipc.html'), name='aipc'),
    path('jaf/', HomepageView.as_view(template_name='main/jaf.html'), name='jaf'),
    path('iaf/', HomepageView.as_view(template_name='main/iaf.html'), name='iaf'),
    path('reachus/', HomepageView.as_view(template_name='main/reachus.html'), name='reachus'),
    path('invitation/', HomepageView.as_view(template_name='main/invitation.html'), name='invitation'),
    path('dir_msg/', HomepageView.as_view(template_name='main/dir_msg.html'), name='dir_msg'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('chairman_msg/', HomepageView.as_view(template_name='main/chairman_msg.html'), name='chairman_msg'),
]

src/main/urls.py
from django.urls import path, include
from .views import HomepageView, NavBarSubOptionsPageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('<slug:slug>/', NavBarSubOptionsPageView.as_view(), name='navbarsuboptionpage')
]

src/student/urls.py
from django.urls import path
from .views import DetailsView, ResumeView, InternshipOffersView, JobOffersView, InquirysFormView, SuggestionsFormView
from accounts.views import StudentRegisterFormView

app_name = 'student'

urlpatterns = [
    path('details/', DetailsView.as_view(), name="detail"),
    path('intern_offers/', InternshipOffersView.as_view(), name='intern-offers'),
    path('job_offers/', JobOffersView.as_view(), name='job-offers'),
    path('resume_upload/', ResumeView.as_view(), name='resume_upload'),
    path('register/', StudentRegisterFormView.as_view(), name='register'),
    path('inquiry/', InquirysFormView.as_view(), name='inquiry'),
    path('suggestion/', SuggestionsFormView.as_view(), name='suggestion'),
]

student/urls.py
from django.urls import path
from .views import DetailsView, ResumeView, InternshipOffersView, JobOffersView
from accounts.views import StudentRegisterFormView

app_name = 'student'

urlpatterns = [
    path('details/', DetailsView.as_view(), name="detail"),
    path('intern_offers/', InternshipOffersView.as_view(), name='intern-offers'),
    path('job_offers/', JobOffersView.as_view(), name='job-offers'),
    path('resume_upload/', ResumeView.as_view(), name='resume_upload'),
    path('register/', StudentRegisterFormView.as_view(), name='register'),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from student.models import ProgramAndBranch
from django.db.models.signals import pre_save, post_delete
import random
from django.core.mail import get_connection, EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.apps import apps


class StudentProfile(models.Model):
    # Choices
    CATEGORY = (
        ('1', 'General'),
        ('2', 'OBC'),
        ('3', 'SC'),
        ('4', 'ST'),
    )
    NATION = (
        ('1', 'Indian'),
        ('2', 'Other'),
    )
    # Validators

    # Model
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roll_no = models.CharField(max_length=11)
    year = models.SmallIntegerField()
    program_branch = models.ForeignKey(ProgramAndBranch, on_delete=models.SET_NULL, null=True)
    # program = models.ForeignKey(Program, on_delete=models.SET_NULL, null=True)
    gpa = models.FloatField()
    ug_gpa = models.FloatField(null=True, blank=True)
    phone = models.CharField(max_length=15)
    dob = models.DateField()
    category = models.CharField(max_length=10, choices=CATEGORY)
    jee_air = models.IntegerField(null=True, blank=True)
    physical_disability = models.BooleanField(default=False)
    nationality = models.CharField(max_length=10, choices=NATION)
    permanent_address = models.TextField()
    current_address = models.TextField()
    x_year = models.SmallIntegerField()
    x_board_name = models.CharField(max_length=100)
    x_percentage = models.CharField(max_length=10)
    xii_year = models.SmallIntegerField()
    xii_board_name = models.CharField(max_length=100)
    xii_percentage = models.CharField(max_length=10)
    banned = models.BooleanField(default=False)
    placed = models.BooleanField(default=False)
    std_image = models.ImageField(default='default.jpg', upload_to='student_images')
    registration_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def student_register_email(self):
        from_email = settings.SPC_EMAIL
        with get_connection(
                username=from_email,
                password=settings.SPC_EMAIL_PASSWORD
        ) as connection:
            subject = "Registered with CDC"
            to_email = [self.user.email, ]
            html_content = render_to_string("accounts/student_register_email.html",
                                            {'username': self.user.username, 'email': self.user.email})
            text_content = strip_tags(html_content)
            message = EmailMultiAlternatives(subject=subject, body=text_content, from_email=from_email, to=to_email,
                                             connection=connection)
            message.attach_alternative(html_content, "text/html")
            message.send()

    def __str__(self):
        return self.user.get_full_name()

    # Used in csv export to get list of all applied offers in string
    def get_all_applied_offers_str(self):
        offers = apps.get_model('company.InternshipAdvertisement').objects.filter(
            id__in=apps.get_model('company.InternshipOffer').objects.filter(student__user=self.user).values_list(
                'profile'))

        offers.union(apps.get_model('company.JobAdvertisement').objects.filter(
            id__in=apps.get_model('company.JobOffer').objects.filter(
                student__user=self.user).values_list(
                'profile')))

        offer_list = ''
        for i in range(offers.count()):
            offer_list += str(offers[i]) + ', '
        return offer_list


class CompanyProfile(models.Model):
    # Choices
    NATION = (
        ('1', 'Indian'),
        ('2', 'Other'),
    )
    # Model
    name = models.CharField(max_length=50, help_text="Name of the company")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    domain = models.CharField(max_length=30, help_text="Type of company like banking/consulting etc ")  # add choices
    url = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=15, null=True, blank=True)
    state = models.CharField(max_length=15, null=True, blank=True)
    country = models.CharField(max_length=15, choices=NATION)
    pin_code = models.CharField(max_length=10, blank=True, null=True)
    job_offers = models.ManyToManyField(StudentProfile, through='company.JobOffer',
                                        through_fields=('company', 'student'), related_name='joboffers')
    internship_offers = models.ManyToManyField(StudentProfile, through='company.InternshipOffer',
                                               through_fields=('company', 'student'), related_name='internshipoffers')
    contact = models.CharField(max_length=20)
    registration_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    def company_register_email(self):
        from_email = settings.SPC_EMAIL
        with get_connection(
                username=from_email,
                password=settings.SPC_EMAIL_PASSWORD
        ) as connection:
            subject = "Registered with CDC"
            to_email = [self.user.username, ]
            html_content = render_to_string("accounts/company_register_email.html", {'username': self.user.username})
            text_content = strip_tags(html_content)
            message = EmailMultiAlternatives(subject=subject, body=text_content, from_email=from_email, to=to_email,
                                             connection=connection)
            message.attach_alternative(html_content, "text/html")
            message.send()

    def company_details_email(self):
        from_email = settings.SPC_EMAIL
        with get_connection(
                username=from_email,
                password=settings.SPC_EMAIL_PASSWORD
        ) as connection:
            subject = "Company Registered with CDC"
            to_email = settings.RECIPIENT_EMAILS
            html_content = render_to_string("accounts/company_details_email.html",
                                            {'name': self.name, 'email': self.user.username,
                                             'domain': self.domain, 'url': self.url,
                                             'city': self.city, 'state': self.state,
                                             'contact': self.contact})
            text_content = strip_tags(html_content)
            message = EmailMultiAlternatives(subject=subject, body=text_content, from_email=from_email, to=to_email,
                                             connection=connection)
            message.attach_alternative(html_content, "text/html")
            message.send()


class CompanyPerson(models.Model):
    name = models.CharField(max_length=30)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
    designation = models.CharField(max_length=30)
    phone = models.CharField(max_length=15, help_text="For phone numbers outside India, please add country code")
    email = models.EmailField()


class Resume(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    file = models.FileField(upload_to='resume')
    is_verified = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    reference = models.CharField(max_length=200, null=True, blank=True,
                                 help_text="Enter a reference name for this resume by which you can remember the details of this particular resume")

    def __str__(self):
        if not self.reference:
            return "No reference"
        else:
            return self.reference


def event_pre_save_receiver_student(sender, instance, *args, **kwargs):
    if not instance.roll_no:
        instance.roll_no = instance.user.username


pre_save.connect(event_pre_save_receiver_student, sender=StudentProfile)


def event_pre_save_receiver_resume(sender, instance, *args, **kwargs):
    if instance.student.user.first_name not in instance.file.name or \
            instance.student.user.last_name not in instance.file.name or \
            instance.student.user.username not in instance.file.name or \
            'IITJodhpur.pdf' not in instance.file.name \
            and instance._state.adding is True:
        instance.file.name = instance.student.user.first_name + '_' + instance.student.user.last_name \
                             + '_' + instance.student.user.username + '_' + str(random.randint(1, 10001)) + \
                             '_' + 'IITJodhpur.pdf'
    if not instance.reference:
        instance.reference = instance.file.name


pre_save.connect(event_pre_save_receiver_resume, sender=Resume)


def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExist:
        pass
    else:
        instance.user.delete()


post_delete.connect(delete_user, sender=StudentProfile)
post_delete.connect(delete_user, sender=CompanyProfile)

student/forms.py
from django import forms
from company.models import JobOffer, InternshipOffer
from accounts.models import Resume


class JobOfferForm(forms.ModelForm):
    resume = forms.ModelChoiceField(queryset=Resume.objects.none(), empty_label='Select Resume')

    def __init__(self, user, *args, **kwargs):
        super(JobOfferForm, self).__init__(*args, **kwargs)
        resumes = Resume.objects.filter(student__user=user, is_verified=True)
        self.fields['resume'].queryset = resumes

    class Meta:
        model = JobOffer
        fields = ('profile', 'student', 'resume',)


class InternshipOfferForm(forms.ModelForm):
    resume = forms.ModelChoiceField(queryset=Resume.objects.none(), empty_label='Select Resume')

    def __init__(self, user, *args, **kwargs):
        super(InternshipOfferForm, self).__init__(*args, **kwargs)
        resumes = Resume.objects.filter(student__user=user, is_verified=True)
        self.fields['resume'].queryset = resumes

    class Meta:
        model = InternshipOffer
        fields = ('profile', 'student', 'resume',)

src/main/views.py
from django.views.generic import TemplateView, DetailView
from .models import CoreTeamContacts, Volunteers, News, AlumniTestimonial, HomeImageCarousel, NavBarSubOptions, \
    CareerCommittee


class HomepageView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data()
        context['carousel'] = HomeImageCarousel.objects.filter(active=True).order_by('ordering')
        context['news_list'] = News.objects.filter(active=True).order_by('order_no')
        context['testimonial_list'] = AlumniTestimonial.objects.filter(active='True').order_by('ranking')
        return context


class NavBarSubOptionsPageView(DetailView):
    template_name = 'main/navbarsuboptionpage.html'
    model = NavBarSubOptions

    def get_context_data(self, **kwargs):
        context = super(NavBarSubOptionsPageView, self).get_context_data()
        context['contacts'] = CoreTeamContacts.objects.filter(active=True).order_by('order_no')
        context['volunteers'] = Volunteers.objects.filter(active=True).order_by('order_no')
        context['c3members'] = CareerCommittee.objects.filter(active=True).order_by('order_no')
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        if self.object.use_custom_html:
            self.template_name = self.object.custom_html
        else:
            self.template_name = 'main/navbarsuboptionpage.html'
        return self.render_to_response(context)

src/templates/student/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    {% block header %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/style1.css' %} " rel="stylesheet">
    <link rel="icon" href="{% static 'img/iitj.png' %}">
    <!--    Google Font APIs-->
    <link href="https://fonts.googleapis.com/css?family=Darker+Grotesque&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--    Google Font APIs-->
    <title>Career Development Cell, IIT Jodhpur</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style type="text/css">
        .row {
            margin-left: 0;
            margin-right: 0;
        }

        .container {
        }

        .row {
            margin-left: -15px;
            margin-right: -15px;
        }
    </style>
    {% endblock %}
</head>
<body style="margin:0px auto ;background-color: white;">
<div class="container-fluid">

    {% block heading %}
    <div class="main-heading">
        <div class="row">
            <div class="col-md-12">
                <div class="media"
                     style="margin-left: auto; margin-bottom: 1px; margin-top: 1rem; margin-right: auto;">
                    <a class="thumbnail pull-left">
                        &nbsp &nbsp
                       
                        <img src="{% static '/img/cdclogo.png' %}" alt="IIT Jodhpur" class="logo",href="/",
                             style="height:5rem; width:auto;">
                            

                    </a>
                    <div class="media-body" style="margin-left:10px; margin-top: 10px;">
                        <a href="http://iitj.ac.in/" class=" pull-right" style="margin-right: 0.5rem"
                           target="_blank">IIT Jodhpur
                            &nbsp; <i class="fa fa-external-link"></i></a>
                        <h4 class="heading big" style="font-weight:400"><a href="http://spc.iitj.ac.in/"
                                                                           style="color: black; font-family: 'Poppins', sans-serif;">Career
                            Development Cell</a></h4>
                        <h6 class="heading" style="margin-top:-0.40rem; font-family: 'Poppins', sans-serif;">IIT
                            JODHPUR </h6>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    {% block navbar %}
    <nav class="navbar navbar-toggleable-md navbar-dark">
        <div class="container">
            <div class=" navbar-collapse" id="collapseEx12">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:resume_upload' %}"
                           style="color: black; font-family: 'Poppins', sans-serif;">Upload Resume</a>
                    </li>
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:detail' %}"
                           style="color: black; font-family: 'Poppins', sans-serif;">Edit Personal Details</a>
                    </li>
                    {# BTech#}
                    {% if request.user.username.0 == 'B' %}
                    {% if request.user.username.2 == '8' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:intern-offers' %}" style="color: black">View Intern
                            Offers</a>
                    </li>
                    {% elif request.user.username.2 <= '7' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:job-offers' %}" style="color: black">View Job
                            Offers</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {# Mtech#}
                    {% if request.user.username.0 == 'M' and request.user.username.1 != 'T' %}
                    {% if request.user.username.2 == '0' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:intern-offers' %}" style="color: black">View Intern Offers</a>
                    </li>
                    {% elif request.user.username.2 <= '9' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:job-offers' %}" style="color: black">View Job Offers</a>
                    </li>
                    {% endif %}
                    {% endif %}

                    {# New Mtech#}
                    {% if request.user.username.0 == 'M' and request.user.username.1 == 'T' %}
                    {% if request.user.username.3 == '0' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:intern-offers' %}" style="color: black">View Intern Offers</a>
                    </li>
                    {% elif request.user.username.3 <= '9' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:job-offers' %}" style="color: black">View Job Offers</a>
                    </li>
                    {% endif %}
                    {% endif %}


                    {#PHD#}
                    {% if request.user.username.0 == 'P' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:intern-offers' %}" style="color: black">View Intern Offers</a>
                    </li>
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:job-offers' %}" style="color: black">View Job Offers</a>
                    </li>
                    {% endif %}
                    {% if request.user.username.0 == 'U' %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:job-offers' %}" style="color: black">View Job Offers</a>
                    </li>
                    {% endif %}
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:suggestion' %}" style="color: black">Suggestion</a>
                    </li>
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'student:inquiry' %}" style="color: black">Inquiry</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav nav-right">
                    <li class="nav-item hoverable" style="float:right;">
                        <a class="nav-link" href="{% url 'logout' %}"
                           style="color: black; font-family: 'Poppins', sans-serif;">Logout</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <br><br>
    {% endblock %}
    {% block body %}

    {% endblock %}

</div>
{% block footer %}
<br>
<footer class="footer-basic-centered">

    <p class="footer-logos" style="color: white; font-size: 2rem;">

        <a href="https://www.facebook.com/SPC.IITJ/" target="_blank"><i class="fa fa-facebook"
                                                                        style="color: black"></i></a>
        <a href="https://www.linkedin.com/in/office-of-student-placements-iit-jodhpur-62a31352/" target="_blank"><i
                class="fa fa-linkedin" style="color: black"></i></a>
        <a href="https://github.com/anshulahuja98/spc_portal" target="_blank"><i class="fa fa-github"
                                                                                 style="color: black"></i></a>

    </p>

    <p class="footer-company-name" style="font-family: 'Poppins', sans-serif;">Designed & Maintained by Career
        Development Cell, IIT Jodhpur</p>

</footer>
<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static '/js/tether.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static '/js/mdb.min.js' %}"></script>

{% endblock %}
</div>
</body>
</html>

src/templates/student/editDetails.html
{% extends 'student/base.html' %}
{% block body %}

{% endblock %}

src/templates/student/message.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="alert aler-sm alert-{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

src/templates/student/resume.html
{% extends 'student/base.html' %}
{% block body %}

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="card">
                <div class="card" id="my-card"><span style="font-size: 1.5rem"> &nbsp; Resume Update</span></div>
                <div class="card-block">
                    <div class="table-responsive">
                        <table class="table table-striped" style="border:1rem;">
                            <thead class="lighten-4">
                            <tr><span class="red-text">{{form.errors}}
                                You can upload a maximum of 7 Resume which cannot be edited later<br>
                            ** After uploading, please click the corresponding RESUME button to check if resume is properly uploaded</span></tr>
                            <tr>
                                <th class="theader">S.No</th>
                                <th class="theader">**Resume</th>
                                <th class="theader">Reference Name</th>
                                <th class="theader">Approval Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for resume in resume_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="{{ resume.file.url }}" target="_blank">
                                        <button class=" btn btn-info btn-sm">
                                            Resume {{ forloop.counter }}
                                        </button>
                                    </a></td>
                                    <td>{{ resume.reference }}</td>
                                    <td>
                                        {% if resume.is_verified %}
                                            <span class="green-text"> Approved</span>
                                        {% else %}
                                            <span class="red-text">Not Approved</span>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <br><br>
                    {% if resume_list.count < 7 %}
                        <form method="post" id="new_resume_upload" enctype=multipart/form-data>
                            {% csrf_token %}
                            <hr>
                            <h4 style="font-weight: normal" align="center">Upload Another Resume:</h4>
                            <hr>

                            <!-- One "tab" for each step in the form: -->
                            <div class="row">
                                <div class="col-lg-1"></div>
                                <div class="col-lg-4">File:
                                    <p><input type="file" name="file" required id="id_file" accept="application/pdf"
                                              class=""
                                              style="padding: 10px;width: 100%;font-size: 17px"/></p>
                                    <span class="red-text">You can only upload PDF Resumes</span>
                                </div>
                                <div class="col-lg-1" style="text-align: right"><br><i class="fa fa-pencil"
                                                                                       style="font-size: 2rem;"></i>
                                </div>
                                <div class="col-lg-6" style="text-align: left">Reference Name:
                                    <p><input placeholder="Reference Name" name="reference" class="form-control"
                                              id="id_reference" oninput="this.className=''"
                                              style="border: 1px solid #aaaaaa;padding: 10px;width: 100%;font-size: 17px"/>
                                    </p>
                                    <p>Enter a reference name for this resume by which
                                        you can remember the details of this particular resume</p>
                                </div>

                                <div class="col-lg-10" style="text-align: center">
                                    <button class="btn btn-primary" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    </div>


{% endblock %}