main/urls.py
from django.urls import path, include
from .views import HomepageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('gradesystem/', HomepageView.as_view(template_name='main/gradesystem.html'), name='gradesystem'),
    path('programs/', HomepageView.as_view(template_name='main/programs.html'), name='programs'),
    path('rules/', HomepageView.as_view(template_name='main/rules.html'), name='rules'),
    path('placementProcedure/', HomepageView.as_view(template_name='main/placementprocedure.html'),
         name='placementProcedure'),
    path('contacts/', HomepageView.as_view(template_name='main/contacts.html'), name='contacts'),
    path('admissions/', HomepageView.as_view(template_name='main/admissions.html'), name='admissions'),
    path('achievements/', HomepageView.as_view(template_name='main/achievements.html'), name='achievements'),
    path('profile/', HomepageView.as_view(template_name='main/prospective.html'), name='profile'),
    path('alumni/', HomepageView.as_view(template_name='main/alumni.html'), name='alumni'),
    path('student_rules/', HomepageView.as_view(template_name='main/student_rules.html'), name='student_rules'),
    path('internships/', HomepageView.as_view(template_name='main/internships.html'), name='internships'),
    path('why_recruit/', HomepageView.as_view(template_name='main/why-recruit.html'), name='why-recruit'),
    path('brochure/', HomepageView.as_view(template_name='main/brochure.html'), name='brochure'),
    path('summary/', HomepageView.as_view(template_name='main/summary.html'), name='summary'),
    path('company_rules/', HomepageView.as_view(template_name='main/company_rules.html'), name='company_rules'),
    path('past_recruiters/', HomepageView.as_view(template_name='main/past_recruiters.html'), name='past_recruiters'),
    path('aipc/', HomepageView.as_view(template_name='main/aipc.html'), name='aipc'),
    path('jaf/', HomepageView.as_view(template_name='main/jaf.html'), name='jaf'),
    path('iaf/', HomepageView.as_view(template_name='main/iaf.html'), name='iaf'),
    path('reachus/', HomepageView.as_view(template_name='main/reachus.html'), name='reachus'),
    path('invitation/', HomepageView.as_view(template_name='main/invitation.html'), name='invitation'),
    path('dir_msg/', HomepageView.as_view(template_name='main/dir_msg.html'), name='dir_msg'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('chairman_msg/', HomepageView.as_view(template_name='main/chairman_msg.html'), name='chairman_msg'),
]

src/accounts/urls.py
# from django.urls import path, include
#
# app_name = 'accounts'
#
# urlpatterns = [
#     path('student/', include('student.urls')),
#     path('company/', include('company.urls')),
#
# ]

src/main/urls.py
from django.urls import path, include
from .views import HomepageView, NavBarSubOptionsPageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('<slug:slug>/', NavBarSubOptionsPageView.as_view(), name='navbarsuboptionpage')
]

src/student/urls.py
from django.urls import path
from .views import DetailsView, ResumeView, InternshipOffersView, JobOffersView, InquirysFormView, SuggestionsFormView
from accounts.views import StudentRegisterFormView

app_name = 'student'

urlpatterns = [
    path('details/', DetailsView.as_view(), name="detail"),
    path('intern_offers/', InternshipOffersView.as_view(), name='intern-offers'),
    path('job_offers/', JobOffersView.as_view(), name='job-offers'),
    path('resume_upload/', ResumeView.as_view(), name='resume_upload'),
    path('register/', StudentRegisterFormView.as_view(), name='register'),
    path('inquiry/', InquirysFormView.as_view(), name='inquiry'),
    path('suggestion/', SuggestionsFormView.as_view(), name='suggestion'),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from student.models import ProgramAndBranch
from django.db.models.signals import pre_save, post_delete
import random
from django.core.mail import get_connection, EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.apps import apps


class StudentProfile(models.Model):
    # Choices
    CATEGORY = (
        ('1', 'General'),
        ('2', 'OBC'),
        ('3', 'SC'),
        ('4', 'ST'),
    )
    NATION = (
        ('1', 'Indian'),
        ('2', 'Other'),
    )
    # Validators

    # Model
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roll_no = models.CharField(max_length=11)
    year = models.SmallIntegerField()
    program_branch = models.ForeignKey(ProgramAndBranch, on_delete=models.SET_NULL, null=True)
    # program = models.ForeignKey(Program, on_delete=models.SET_NULL, null=True)
    gpa = models.FloatField()
    ug_gpa = models.FloatField(null=True, blank=True)
    phone = models.CharField(max_length=15)
    dob = models.DateField()
    category = models.CharField(max_length=10, choices=CATEGORY)
    jee_air = models.IntegerField(null=True, blank=True)
    physical_disability = models.BooleanField(default=False)
    nationality = models.CharField(max_length=10, choices=NATION)
    permanent_address = models.TextField()
    current_address = models.TextField()
    x_year = models.SmallIntegerField()
    x_board_name = models.CharField(max_length=100)
    x_percentage = models.CharField(max_length=10)
    xii_year = models.SmallIntegerField()
    xii_board_name = models.CharField(max_length=100)
    xii_percentage = models.CharField(max_length=10)
    banned = models.BooleanField(default=False)
    placed = models.BooleanField(default=False)
    std_image = models.ImageField(default='default.jpg', upload_to='student_images')
    registration_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def student_register_email(self):
        from_email = settings.SPC_EMAIL
        with get_connection(
                username=from_email,
                password=settings.SPC_EMAIL_PASSWORD
        ) as connection:
            subject = "Registered with CDC"
            to_email = [self.user.email, ]
            html_content = render_to_string("accounts/student_register_email.html",
                                            {'username': self.user.username, 'email': self.user.email})
            text_content = strip_tags(html_content)
            message = EmailMultiAlternatives(subject=subject, body=text_content, from_email=from_email, to=to_email,
                                             connection=connection)
            message.attach_alternative(html_content, "text/html")
            message.send()

    def __str__(self):
        return self.user.get_full_name()

    # Used in csv export to get list of all applied offers in string
    def get_all_applied_offers_str(self):
        offers = apps.get_model('company.InternshipAdvertisement').objects.filter(
            id__in=apps.get_model('company.InternshipOffer').objects.filter(student__user=self.user).values_list(
                'profile'))

        offers.union(apps.get_model('company.JobAdvertisement').objects.filter(
            id__in=apps.get_model('company.JobOffer').objects.filter(
                student__user=self.user).values_list(
                'profile')))

        offer_list = ''
        for i in range(offers.count()):
            offer_list += str(offers[i]) + ', '
        return offer_list


class CompanyProfile(models.Model):
    # Choices
    NATION = (
        ('1', 'Indian'),
        ('2', 'Other'),
    )
    # Model
    name = models.CharField(max_length=50, help_text="Name of the company")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    domain = models.CharField(max_length=30, help_text="Type of company like banking/consulting etc ")  # add choices
    url = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=15, null=True, blank=True)
    state = models.CharField(max_length=15, null=True, blank=True)
    country = models.CharField(max_length=15, choices=NATION)
    pin_code = models.CharField(max_length=10, blank=True, null=True)
    job_offers = models.ManyToManyField(StudentProfile, through='company.JobOffer',
                                        through_fields=('company', 'student'), related_name='joboffers')
    internship_offers = models.ManyToManyField(StudentProfile, through='company.InternshipOffer',
                                               through_fields=('company', 'student'), related_name='internshipoffers')
    contact = models.CharField(max_length=20)
    registration_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    def company_register_email(self):
        from_email = settings.SPC_EMAIL
        with get_connection(
                username=from_email,
                password=settings.SPC_EMAIL_PASSWORD
        ) as connection:
            subject = "Registered with CDC"
            to_email = [self.user.username, ]
            html_content = render_to_string("accounts/company_register_email.html", {'username': self.user.username})
            text_content = strip_tags(html_content)
            message = EmailMultiAlternatives(subject=subject, body=text_content, from_email=from_email, to=to_email,
                                             connection=connection)
            message.attach_alternative(html_content, "text/html")
            message.send()

    def company_details_email(self):
        from_email = settings.SPC_EMAIL
        with get_connection(
                username=from_email,
                password=settings.SPC_EMAIL_PASSWORD
        ) as connection:
            subject = "Company Registered with CDC"
            to_email = settings.RECIPIENT_EMAILS
            html_content = render_to_string("accounts/company_details_email.html",
                                            {'name': self.name, 'email': self.user.username,
                                             'domain': self.domain, 'url': self.url,
                                             'city': self.city, 'state': self.state,
                                             'contact': self.contact})
            text_content = strip_tags(html_content)
            message = EmailMultiAlternatives(subject=subject, body=text_content, from_email=from_email, to=to_email,
                                             connection=connection)
            message.attach_alternative(html_content, "text/html")
            message.send()


class CompanyPerson(models.Model):
    name = models.CharField(max_length=30)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
    designation = models.CharField(max_length=30)
    phone = models.CharField(max_length=15, help_text="For phone numbers outside India, please add country code")
    email = models.EmailField()


class Resume(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    file = models.FileField(upload_to='resume')
    is_verified = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    reference = models.CharField(max_length=200, null=True, blank=True,
                                 help_text="Enter a reference name for this resume by which you can remember the details of this particular resume")

    def __str__(self):
        if not self.reference:
            return "No reference"
        else:
            return self.reference


def event_pre_save_receiver_student(sender, instance, *args, **kwargs):
    if not instance.roll_no:
        instance.roll_no = instance.user.username


pre_save.connect(event_pre_save_receiver_student, sender=StudentProfile)


def event_pre_save_receiver_resume(sender, instance, *args, **kwargs):
    if instance.student.user.first_name not in instance.file.name or \
            instance.student.user.last_name not in instance.file.name or \
            instance.student.user.username not in instance.file.name or \
            'IITJodhpur.pdf' not in instance.file.name \
            and instance._state.adding is True:
        instance.file.name = instance.student.user.first_name + '_' + instance.student.user.last_name \
                             + '_' + instance.student.user.username + '_' + str(random.randint(1, 10001)) + \
                             '_' + 'IITJodhpur.pdf'
    if not instance.reference:
        instance.reference = instance.file.name


pre_save.connect(event_pre_save_receiver_resume, sender=Resume)


def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExist:
        pass
    else:
        instance.user.delete()


post_delete.connect(delete_user, sender=StudentProfile)
post_delete.connect(delete_user, sender=CompanyProfile)

src/student/models.py
from django.db import models
from django.utils.deconstruct import deconstructible


@deconstructible
class ProgramAndBranch(models.Model):
    name = models.CharField(max_length=60)
    abbreviation = models.CharField(max_length=10)
    usable = models.BooleanField(default=False)

    def __str__(self):
        return self.abbreviation


class ProgramEmailId(models.Model):
    program = models.ForeignKey(ProgramAndBranch, on_delete=models.CASCADE)
    year = models.IntegerField(blank=True, null=True)
    email = models.EmailField()

    def __str__(self):
        return self.email

src/main/views.py
from django.views.generic import TemplateView, DetailView
from .models import CoreTeamContacts, Volunteers, News, AlumniTestimonial, HomeImageCarousel, NavBarSubOptions, \
    CareerCommittee


class HomepageView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data()
        context['carousel'] = HomeImageCarousel.objects.filter(active=True).order_by('ordering')
        context['news_list'] = News.objects.filter(active=True).order_by('order_no')
        context['testimonial_list'] = AlumniTestimonial.objects.filter(active='True').order_by('ranking')
        return context


class NavBarSubOptionsPageView(DetailView):
    template_name = 'main/navbarsuboptionpage.html'
    model = NavBarSubOptions

    def get_context_data(self, **kwargs):
        context = super(NavBarSubOptionsPageView, self).get_context_data()
        context['contacts'] = CoreTeamContacts.objects.filter(active=True).order_by('order_no')
        context['volunteers'] = Volunteers.objects.filter(active=True).order_by('order_no')
        context['c3members'] = CareerCommittee.objects.filter(active=True).order_by('order_no')
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        if self.object.use_custom_html:
            self.template_name = self.object.custom_html
        else:
            self.template_name = 'main/navbarsuboptionpage.html'
        return self.render_to_response(context)

src/templates/main/mixins/c3member_card_mixin.html
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3" style="margin: auto;margin-bottom: 2.5rem;">
    <div class="card border-dark mb-3">
        <div class="card text-center " style="margin-right: 0rem; margin-left: 0rem;">
            <!--            <div class="card-header" style="font-size: 1.15rem; background-color: #f5f5f5; ">&nbsp;-->
            <!--                <b>{{ c3member.department }}</b>-->
            <!--            </div>-->
            <div class="card-body" style="background-color: white">
                {% if c3member.profile_image %}
                <img src="{{ c3member.profile_image.url }}" alt="{{c3member.name}}"
                     style="height: 12rem; width: 10rem; margin: auto; margin-top: 0.5rem; margin-bottom: 0.5rem;border-radius: 0.25rem">
                {% endif %}
            </div>
            <div class="card-footer text-muted" style="background-color: #f5f5f5">
                <span style="color: black; font-size: 1.35rem"><b>{{c3member.name}}</b></span>
                <div class="card-header" style="font-size: 1.15rem; background-color: #f5f5f5; ">&nbsp;
                    <b>{{ c3member.department }}</b>
                </div>
                <p class="text-left">
                <table>
                    <tr>
                        <td align="left">&nbsp;{% if c3member.email %}
                            <span style="color: black"><i class="fa fa-envelope"></i>&nbsp; {{c3member.email}}</span>
                            {% endif %}
                        </td>
                    </tr>
                </table>
                </p>
            </div>
        </div>
    </div>
</div>

src/templates/main/mixins/contact_card_mixin.html
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3" style="margin: auto;margin-bottom: 2.5rem;">
    <div class="card border-dark mb-3">
        <div class="card text-center " style="margin-right: 0rem; margin-left: 0rem;">
            <div class="card-header" style="font-size: 1.15rem; background-color: #f5f5f5; "><i
                    class="fa fa-star-o"></i> &nbsp;
                <b> {% if contact.designation == '5' or contact.designation == '6' %}
                    {{contact.get_designation_display}}</b><br>{{contact.program_branch}}
                {% else %}
                {{contact.get_designation_display}}</b><br>{{contact.sub_designation}}
                {% endif %}
            </div>
            <div class="card-body" style="background-color: white">
                {% if contact.profile_image %}
                <img src="{{ contact.profile_image.url }}" alt="{{contact.user.get_full_name}}"
                     style="height: 12rem; width: 10rem; margin: auto; margin-top: 0.5rem; margin-bottom: 0.5rem;border-radius: 0.25rem">
                {% endif %}
            </div>
            <div class="card-footer text-muted" style="background-color: #f5f5f5">
                <span style="color: black; font-size: 1.35rem"><b>{{contact.user.get_full_name}}</b></span>
                <br>
                <p class="text-left">
                <table>
                    <tr><td align="left">&nbsp;{% if contact.user.email %}
                        <span style="color: black"><i class="fa fa-envelope"></i>&nbsp; {{contact.user.email}}</span>
                        {% endif %}</td>
                    </tr>
                    <tr><td align="left">&nbsp;{% if contact.phone %}

                        <span style="color: black"><i class="fa fa-phone"></i>&nbsp; {{contact.phone}}</span>
                        {% endif %}</td>
                    </tr>
                    <tr><td align="left">&nbsp;{% if contact.github_link and contact.get_github_username %}

                        <span style="color: black"><a href="{{contact.github_link}}" target="_blank">
                        <i class="fa fa-github" style="font-size: 1.5rem;"></i>&nbsp; github@{{contact.get_github_username}}</a></span>
                         {% endif %}</td>
                    </tr>
                    <tr><td align="left">&nbsp;{% if contact.linkedin_link and contact.get_linkedin_username %}

                        <span style="color: black"><a href="{{contact.linkedin_link}}" target="_blank">
                        <i class="fa fa-linkedin" style="font-size: 1.5rem;"></i>&nbsp; linkedin@{{contact.get_linkedin_username}}</a></span>

                        {% endif %}</td>
                    </tr>
                </table>
                </p>
            </div>
        </div>
    </div>
</div>

src/templates/main/mixins/recruiters_mixin.html
{% load staticfiles %}
<div id="past_recruiters">
    <center>
        <h4 style="background: #f5f5f5; font-family: 'Poppins', sans-serif;"><b>

            <font color="black"> Past &nbsp Recruiters</font>

        </b></h4>
    </center>
    <br>
    <div class="marquee_spc">
        <marquee BEHAVIOR="alternate" direction="up" HEIGHT=600 scrollamount="4" onmouseover="this.stop();"
                 onmouseout="this.start();">
            {% for company in companies %}
            <br>
            {% if company.company_logo %}
            <img class="d-block w-100" src="{{ company.company_logo.url }} " alt="{{ company.company_name }}">
            {% elif company.company_name %}
            {{ company.company_name }}
            {% endif %}
            {% endfor %}
            <br>
        </marquee>
    </div>
</div>