company/urls.py
from django.urls import path
from .views import InternshipAdvertisementFormView, JobAdvertisementFormView, InternshipAdvertisementAddedListView, \
    JobAdvertisementsAddedListView, \
    InternshipOfferView, JobOfferView
from accounts.views import CompanyRegisterFormView

app_name = 'company'

urlpatterns = [
    path('intern_offers/', InternshipAdvertisementAddedListView.as_view(), name='intern-offers-added'),
    path('job_offers/', JobAdvertisementsAddedListView.as_view(), name='job-offers-added'),
    path('joboffer_form/', JobAdvertisementFormView.as_view(), name="job-offer-form"),
    path('internoffer_form/', InternshipAdvertisementFormView.as_view(), name="intern-offer-form"),
    path('internship_offer/<uuid:id>/', InternshipOfferView.as_view(), name="internship-offer"),
    path('job_offer/<uuid:id>/', JobOfferView.as_view(), name="job-offer"),
    path('register/', CompanyRegisterFormView.as_view(), name='register'),

]

main/urls.py
from django.urls import path, include
from .views import HomepageView

app_name = 'main'

urlpatterns = [
    path('', HomepageView.as_view(template_name='main/index.html'), name='home'),
    path('gradesystem/', HomepageView.as_view(template_name='main/gradesystem.html'), name='gradesystem'),
    path('programs/', HomepageView.as_view(template_name='main/programs.html'), name='programs'),
    path('rules/', HomepageView.as_view(template_name='main/rules.html'), name='rules'),
    path('placementProcedure/', HomepageView.as_view(template_name='main/placementprocedure.html'),
         name='placementProcedure'),
    path('contacts/', HomepageView.as_view(template_name='main/contacts.html'), name='contacts'),
    path('admissions/', HomepageView.as_view(template_name='main/admissions.html'), name='admissions'),
    path('achievements/', HomepageView.as_view(template_name='main/achievements.html'), name='achievements'),
    path('profile/', HomepageView.as_view(template_name='main/prospective.html'), name='profile'),
    path('alumni/', HomepageView.as_view(template_name='main/alumni.html'), name='alumni'),
    path('student_rules/', HomepageView.as_view(template_name='main/student_rules.html'), name='student_rules'),
    path('internships/', HomepageView.as_view(template_name='main/internships.html'), name='internships'),
    path('why_recruit/', HomepageView.as_view(template_name='main/why-recruit.html'), name='why-recruit'),
    path('brochure/', HomepageView.as_view(template_name='main/brochure.html'), name='brochure'),
    path('summary/', HomepageView.as_view(template_name='main/summary.html'), name='summary'),
    path('company_rules/', HomepageView.as_view(template_name='main/company_rules.html'), name='company_rules'),
    path('past_recruiters/', HomepageView.as_view(template_name='main/past_recruiters.html'), name='past_recruiters'),
    path('aipc/', HomepageView.as_view(template_name='main/aipc.html'), name='aipc'),
    path('jaf/', HomepageView.as_view(template_name='main/jaf.html'), name='jaf'),
    path('iaf/', HomepageView.as_view(template_name='main/iaf.html'), name='iaf'),
    path('reachus/', HomepageView.as_view(template_name='main/reachus.html'), name='reachus'),
    path('invitation/', HomepageView.as_view(template_name='main/invitation.html'), name='invitation'),
    path('dir_msg/', HomepageView.as_view(template_name='main/dir_msg.html'), name='dir_msg'),
    path('student/', include('student.urls')),
    path('company/', include('company.urls')),
    path('tutorial_student/', HomepageView.as_view(template_name='main/tutorial-student.html'),
         name='tutorial_student'),
    path('tutorial_company/', HomepageView.as_view(template_name='main/tutorial-company.html'), name='tutorial_company'),
    path('chairman_msg/', HomepageView.as_view(template_name='main/chairman_msg.html'), name='chairman_msg'),
]

src/spc_django/urls.py
from django.urls import path, include
from django.contrib import admin
from accounts.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

admin.site.site_title = 'SPC Administration'
admin.site.site_header = 'SPC Administration'
admin.site.index_title = 'Admin Panel'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('student/', include('student.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            html_email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>[0-9A-Za-z_-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/company/models.py
from django.db import models
from uuid import uuid4
from django.shortcuts import reverse
from accounts.models import CompanyProfile, StudentProfile, Resume
from student.models import ProgramAndBranch, ProgramEmailId
from django.db.models.signals import pre_save
from django.utils.html import format_html


class BaseAdvertisement(models.Model):
    # validity
    expiry = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=False)
    # job prof
    id = models.UUIDField(primary_key=True, default=uuid4)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
    designation = models.CharField(max_length=250)
    description = models.TextField()
    tentative_join_date = models.DateField()
    tentative_job_location = models.CharField(max_length=50)
    ads = models.FileField(upload_to='ads', null=True, blank=True)
    # package details
    ctc = models.FloatField()
    gross_salary = models.FloatField(null=True, blank=True)
    bonus = models.CharField(blank=True, null=True, max_length=100)
    bond = models.BooleanField()
    bond_details = models.TextField(blank=True, null=True)
    # selection process
    eligible_program_branch = models.ManyToManyField(ProgramAndBranch, default=ProgramAndBranch.objects.all())
    resume_required = models.BooleanField()
    resume_shortlist_criteria = models.TextField(null=True, blank=True)
    aptitude_test_required = models.BooleanField()
    group_discussion_required = models.BooleanField()
    number_of_technical_interviews = models.PositiveSmallIntegerField(default=0)
    number_of_technical_tests = models.PositiveSmallIntegerField(default=0)
    number_of_hr_rounds = models.PositiveSmallIntegerField(default=0)
    medical_test_required = models.BooleanField()
    min_gpa = models.FloatField()
    number_of_members = models.PositiveIntegerField(null=True, blank=True)
    other_details = models.TextField(null=True, blank=True)
    email_ids = models.ManyToManyField(ProgramEmailId, blank=True)
    email_sent = models.BooleanField(default=False)
    creation_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return "{} ({})".format(self.designation, self.company.name)


class JobAdvertisement(BaseAdvertisement):
    pass

    def get_absolute_url(self):
        return reverse("company:job-offer", kwargs={"id": self.id})

    def get_offers(self):
        return JobOffer.objects.filter(profile__id=self.id)


class InternshipAdvertisement(BaseAdvertisement):
    pass

    def get_absolute_url(self):
        return reverse("company:internship-offer", kwargs={"id": self.id})

    def get_offers(self):
        return InternshipOffer.objects.filter(profile__id=self.id)


class BaseOffer(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE, null=True)
    company = models.ForeignKey(CompanyProfile, on_delete=models.SET_NULL, null=True)
    is_accepted = models.BooleanField(default=False)
    ppo = models.BooleanField(default=False)
    resume = models.ForeignKey(Resume, on_delete=models.PROTECT, null=True)
    application_timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    @property
    def ctc(self):
        return self.profile.ctc

    def __str__(self):
        return "{} ({}) - {}".format(self.student.user.username, self.profile.designation,
                                     self.company.name)

    class Meta:
        abstract = True

    def get_file(self):
        if self.resume and self.resume.file:
            return format_html('<a href="%s">Resume </a>' % (self.resume.file.url))
        else:
            return 'None'

    def get_roll_no(self):
        return self.student.user.username


class JobOffer(BaseOffer):
    profile = models.ForeignKey(JobAdvertisement, on_delete=models.CASCADE)


class InternshipOffer(BaseOffer):
    profile = models.ForeignKey(InternshipAdvertisement, on_delete=models.CASCADE)


def event_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.company:
        instance.company = instance.profile.company
    if instance.ppo and not instance.is_accepted:
        instance.is_accepted = True


pre_save.connect(event_pre_save_receiver, sender=InternshipOffer)

pre_save.connect(event_pre_save_receiver, sender=JobOffer)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Resume
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from .models import CompanyProfile, StudentProfile
from student.models import ProgramAndBranch


class ResumeForm(forms.ModelForm):
    file = forms.FileField()

    class Meta:
        model = Resume
        fields = ('file', 'reference', 'student')


class StudentRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Enter the same password as before, for verification.',
    )
    username = forms.CharField(max_length=11, help_text="Enter your Roll number, this will be used to login")
    year = forms.IntegerField(max_value=10, help_text="Enter value between 1-5, the current year of your degree")
    #program_branch = forms.ModelChoiceField(queryset=ProgramAndBranch.objects.all())
    gpa = forms.FloatField(max_value=10.00)
    ug_gpa = forms.FloatField(max_value=10.00, required=False)
    phone = forms.CharField(max_length=15)
    dob = forms.DateField()
    category = forms.ChoiceField(choices=StudentProfile.CATEGORY)
    jee_air = forms.IntegerField(required=False)
    physical_disability = forms.BooleanField(required=False)
    nationality = forms.ChoiceField(choices=StudentProfile.NATION)
    permanent_address = forms.CharField(widget=forms.Textarea)
    current_address = forms.CharField(widget=forms.Textarea)
    x_year = forms.IntegerField(max_value=2050, min_value=1980)
    x_board_name = forms.CharField(max_length=100)
    x_percentage = forms.CharField(max_length=10)
    xii_year = forms.IntegerField(max_value=2050, min_value=1980)
    xii_board_name = forms.CharField(max_length=100)
    xii_percentage = forms.CharField(max_length=16)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email']


class CompanyRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Enter the same password as before, for verification.',
    )
    username = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'maxlength': '254'}),
        help_text="This Email ID will be your username")
    name = forms.CharField(max_length=50, help_text="Name of the company")
    domain = forms.CharField(max_length=15, help_text="Type of company like banking/consulting etc ", required=False)
    url = forms.CharField(required=False)
    city = forms.CharField(max_length=15, required=False)
    state = forms.CharField(max_length=15, required=False)
    country = forms.ChoiceField(choices=CompanyProfile.NATION)
    pin_code = forms.CharField(max_length=10, required=False)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

company/forms.py
from django.forms import ModelForm
from .models import JobAdvertisement, InternshipAdvertisement


class JobAdvertisementForm(ModelForm):
    class Meta:
        model = JobAdvertisement
        exclude = ('id',)


class InternshipAdvertisementForm(ModelForm):
    class Meta:
        model = InternshipAdvertisement
        exclude = ('id', 'gross_salary',)

templates/company/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    {% block header %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
        <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static '/css/mdb.min.css' %}" rel="stylesheet">
        <link href="{% static '/css/style.css' %} " rel="stylesheet">
        <link rel="icon" href="{% static 'img/iitj.png' %}">
        <title>Office of Student Placements, IIT Jodhpur</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% endblock %}
</head>
<body style="margin:0px auto ;background-color:#e8f5e9;">
{% block heading %}
<div class="container-fluid">
    <div class="main-heading">
        <div class="row">
            <div class="col-md-12">
                <div class="media" style="margin-left: auto; margin-bottom: 1px; margin-top: 1rem; margin-right: auto;">
                    <a class="thumbnail pull-left">
                        &nbsp &nbsp
                        <img src="{% static '/img/logo2.png' %}" alt="IIT Jodhpur" class="logo"
                             style="height:5rem; width:auto;">
                    </a>
                   <div class="media-body" style="margin-left:10px; margin-top: 10px;">
                    <a href="http://iitj.ac.in/" class=" pull-right" style="margin-right: 0.5rem" target="_blank">IIT Jodhpur &nbsp; <i class="fa fa-external-link"></i></a>
                    <h4 class="heading big" style="font-weight:400"><a href="http://spc.iitj.ac.in/"
                                                                       style="color: black;" >Office of Student
                        Placements</a></h4>
                    <h6 class="heading" style="margin-top:-0.40rem;">IIT JODHPUR </h6>
                    <br>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-toggleable-md navbar-dark">
        <div class="container">
            <div class=" navbar-collapse" id="collapseEx12">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'company:job-offers-added' %}"> Job Offers Added</a>
                    </li>
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'company:intern-offers-added' %}">Intern Offers Added</a>
                    </li>
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'company:job-offer-form' %}">Add Job Offer</a>
                    </li>
                    <li class="nav-item hoverable">
                        <a class="nav-link" href="{% url 'company:intern-offer-form' %}">Add Intern Offer</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav nav-right">
                    <li class="nav-item hoverable" style="float:right;">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br><br>
{% endblock %}
<div>
{% block body %}



{% endblock %}
</div>
</div>
{% block footer %}
 <br>
    <footer class="footer-basic-centered">

            <p class="footer-logos" style="color: white; font-size: 2rem;">

				<a href="https://www.facebook.com/SPC.IITJ/" target="_blank"><i class="fa fa-facebook" style="color: #FFFFFF"></i></a>
				|
				<a href="https://www.linkedin.com/in/office-of-student-placements-iit-jodhpur-62a31352/" target="_blank"><i class="fa fa-linkedin" style="color: #FFFFFF"></i></a>
				|
				<a href="https://github.com/anshulahuja98/spc_portal" target="_blank"><i class="fa fa-github" style="color: #FFFFFF"></i></a>

			</p>

			<p class="footer-company-name">Designed & Maintained by Office of Student Placements, IIT Jodhpur</p>

	</footer>

    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static '/js/tether.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static '/js/mdb.min.js' %}"></script>


{% endblock %}
</div>
</body>
</html>

templates/company/internoffer_form.html
{% extends 'company/base.html' %}
{% block body %}
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <form method="post">
                {% csrf_token %}

                <div class="card">
                    <div class="card" id="my-card"><span style="font-size: 1.5rem"> &nbsp; Add Intern Offer</span></div>
                    <div class="card-block">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                        {% endfor %}
                        <div class="row">
                            <div class="col-lg-1"></div>
                            <div class="col-lg-4">
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-briefcase prefix" style="color: cornflowerblue"></i>
                                    <label for="id_designation" style="font-size: medium; font-weight: bold">Designation:</label>
                                    <input type="text" name="designation" maxlength="30" id="id_designation" required/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-briefcase prefix" style="color:cornflowerblue"></i>
                                    <label for="id_description" style="font-size: medium; font-weight: bold">Description:</label>
                                    {{ form.description }}
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-calendar prefix" style="color:cornflowerblue"></i>
                                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tentative Joining Date:</span>
                                    <input type="date" name="tentative_join_date" id="id_tentative_join_date" required/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-map-marker prefix" style="color: cornflowerblue"></i>
                                    <label for="id_tentative_Intern_location"
                                           style="font-size: medium; font-weight: bold">Tentative
                                        Internship Location:</label> <input type="text" name="tentative_job_location"
                                                                            id="id_tentative_job_location" required/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-fax prefix" style="color: cornflowerblue"></i>
                                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ads : </span>
                                    <input type="file" name="ads" id="id_ads"/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-rupee prefix" style="color:cornflowerblue"></i>
                                    <label for="id_ctc" style="font-size: medium; font-weight: bold">Stipend per month:</label> <input
                                        type="number" name="ctc" id="id_ctc" step="any" required/>
                                </div>
                                <br>
{#                                <div class="md-form">#}
{#                                    <i class="fa fa-rupee prefix" style="color:cornflowerblue"></i>#}
{#                                    <label for="id_gross_salary" style="font-size: medium; font-weight: bold">Gross#}
{#                                        Salary:</label> <input type="number" name="gross_salary" id="id_gross_salary"#}
{#                                                               required step="any"/>#}
{#                                </div>#}
                                <div class="md-form">
                                    <i class="fa fa-gift prefix" style="color:cornflowerblue"></i>
                                    <label for="id_bonus" style="font-size: medium; font-weight: bold">Other Benefits:</label>
                                    <input type="text" name="bonus" id="id_bonus" min="0"/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-plus-circle" style="color:cornflowerblue; font-size:xx-large"></i>
                                    <span>&nbsp;&nbsp;&nbsp;Bond : </span><input type="checkbox" name="bond"
                                                                                 id="id_bond"/>
                                </div>
                                <div class="md-form">

                                    <i class="fa fa-plus-circle" style="color:cornflowerblue; font-size:xx-large"></i>
                                    <span>&nbsp;&nbsp;&nbsp;Bond Details : {{ form.bond_details }}</span>
                                </div>
                            </div>
                            <div class="col-lg-1"></div>
                            <div class="col-lg-5">
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-check" style="color:cornflowerblue; font-size:xx-large"></i>
                                    <span>&nbsp;&nbsp;Eligible Branches and Programs : </span><br>&nbsp;
                                    <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                                        {{ form.eligible_program_branch }}
                                        <br>
                                        <span class="green-text">Press Ctrl and click to select</span>

                                    </div>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-check" style="color:cornflowerblue; font-size:xx-large"></i>
                                    <span>&nbsp;&nbsp;Selection Procedure includes : </span><br>&nbsp;
                                    <table border="0">

                                        <tr>
                                            <td><span style="font-size: large">Resume Shortlist</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td><input type="checkbox" name="resume_required"
                                                       id="id_resume_required"/>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><span style="font-size: large">Resume Shortlist Criteria</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td>{{ form.resume_shortlist_criteria }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><span style="font-size: large">Number of Technical Tests</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td>{{ form.number_of_technical_tests }}</td>
                                        </tr>
                                        <tr>
                                            <td><span style="font-size: large">Number of Technical Interview</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td>{{ form.number_of_technical_interviews }}</td>
                                        </tr>
                                        <tr>
                                            <td><span style="font-size: large">Number of HR Round Interview</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td>{{ form.number_of_hr_rounds }}</td>
                                        </tr>
                                        <tr>
                                            <td><span style="font-size: large">Aptitude Test</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td><input type="checkbox" name="aptitude_test_required"
                                                       id="id_aptitude_test_required"/></td>
                                        </tr>

                                        <tr>
                                            <td><span style="font-size: large">Group Discussion</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td><input type="checkbox" name="group_discussion_required"
                                                       id="id_group_discussion_required"/></td>
                                        </tr>


                                        <tr>
                                            <td><span style="font-size: large">Medical Test Required</span></td>
                                            <td>&nbsp;:&nbsp;&nbsp;</td>
                                            <td><input type="checkbox" name="medical_test_required"
                                                       id="id_medical_test_required"/></td>
                                        </tr>
                                    </table>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-percent prefix" style="color: cornflowerblue"></i>
                                    <label for="id_min_gpa" style="font-size: medium; font-weight: bold">Minimum
                                        CGPA:</label> <input type="number" name="min_gpa" step="any" required
                                                             id="id_min_gpa" value="0"/>
                                </div>
                                <br>
                                <i class="fa fa-car" style="color:cornflowerblue; font-size:xx-large"></i>
                                <span>&nbsp;&nbsp;Details for Logistics</span>
                                <br><br>
                                <div class="md-form">

                                    <i class="fa fa-group prefix" style="color: cornflowerblue"></i>
                                    <label for="id_number_of_members" style="font-size: medium; font-weight: bold">Number
                                        of
                                        Members:</label> <input type="number" name="number_of_members"
                                                                id="id_number_of_members" min="0"/>
                                </div>
                                <br>
                                <div class="md-form">
                                    <i class="fa fa-pencil prefix" style="color: cornflowerblue"></i>
                                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Other Details : </span>
                                    <textarea name="other_details" id="id_other_details" ></textarea>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                            <button class="btn btn-primary btn-lg" type="submit">Create Intern Offer</button>
                        </div>
                        <div class="col-md-4"></div>
                    </div>
                    <br><br>
                </div>
            </form>
            <div class="col-lg-1"></div>
        </div>
    </div>
    </div>
{% endblock %}